{% set name = "feynpy" %}
{% set version = "0.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source: 
  url: https://files.pythonhosted.org/packages/66/df/3e3629a79659d98c7b659b87cf1215511677b090baefd5c66be0398bead1/feynpy-0.0.2.tar.gz
  sha256: 1eed9ca5ada1811583bb93fcf370b664badb45699880968d12446afd40e8a9f4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - feynpy

about:
  home: https://github.com/FeynPy/feynpy
  license: GPLv3
  license_family: GPL
  summary: Python package for QFT calculations
