{% set name = "feynpy" %}
{% set version = "0.0.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source: 
  url: https://test-files.pythonhosted.org/packages/03/18/a5e58dcc1fb5acebea9f352dd81616be2015cbc9fc5956de01f9e1845746/feynpy-0.0.1.tar.gz
  sha256: 1eed9ca5ada1811583bb93fcf370b664badb45699880968d12446afd40e8a9f4

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - feynpy

about:
  home: https://github.com/FeynPy/feynpy
  license: GPLv3
  license_family: GPL
  summary: Python package for QFT calculations
